name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install packages
        run: yarn install --immutable
      - name: Lint Code
        run: yarn lint
      - name: Build app
        run: yarn build
      - name: Run tests
        run: yarn test
